name: GetScreen Windows (6H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=Yedunit12@gmail.com" > secrets.txt
         Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
         cmd /c down.bat

      - name: Time Counter
        run: python time.py
